# Задание 1

### Напишите функцию, которая классифицирует фильмы из материалов занятия по правилам:

- оценка 2 и ниже — низкий рейтинг;
- оценка 4 и ниже — средний рейтинг;
- оценка 4.5 и 5 — высокий рейтинг.
##### Результат классификации запишите в столбец class.

In [1]:
import pandas as pd
from tornado.gen import Return

In [4]:
df_movies = pd.read_csv('C:\\Users\\User\\Desktop\\Аналитик данных\\ДЗ\\ДЗ 10 классы\\movies.csv', sep=',', encoding='utf-8')

In [5]:
df_ratings = pd.read_csv('C:\\Users\\User\\Desktop\\Аналитик данных\\ДЗ\\ДЗ 10 классы\\ratings.csv', sep=',', encoding='utf-8')

In [3]:
df_movies.head(5) #чтение файла с фильмами

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [6]:
df_ratings.head(5)

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [18]:
# пишу функцию для условий оценки
def class_rating(ocenka):
    '''
- оценка 2 и ниже — низкий рейтинг;
- оценка 4 и ниже — средний рейтинг;
- оценка 4.5 и 5 — высокий рейтинг.
    '''
    if ocenka <= 2.0:
        return 'низкий рейтинг'
    elif ocenka > 2.0 and ocenka <=4.0:
        return 'средний рейтинг'
    elif ocenka >= 4.5 and ocenka <=5.0:
        return 'высокий рейтинг'
    else:
        return 'между 4 и 4.5'

In [19]:
# применяю функцию к файлу с рейтингами по столбцу рейтинг и создаю новый столбец класс
df_ratings['class'] = df_ratings['rating'].apply(class_rating)
df_ratings

        userId  movieId  rating   timestamp            class
0            1       31     2.5  1260759144  средний рейтинг
1            1     1029     3.0  1260759179  средний рейтинг
2            1     1061     3.0  1260759182  средний рейтинг
3            1     1129     2.0  1260759185   низкий рейтинг
4            1     1172     4.0  1260759205  средний рейтинг
...        ...      ...     ...         ...              ...
99999      671     6268     2.5  1065579370  средний рейтинг
100000     671     6269     4.0  1065149201  средний рейтинг
100001     671     6365     4.0  1070940363  средний рейтинг
100002     671     6385     2.5  1070979663  средний рейтинг
100003     671     6565     3.5  1074784724  средний рейтинг

[100004 rows x 5 columns]

In [23]:
df_ratings[df_ratings['class'] == 'между 4 и 4.5']

Empty DataFrame
Columns: [userId, movieId, rating, timestamp, class]
Index: []

# Задание 2
### Используйте файл keywords.csv.
Нужно написать гео-классификатор, который каждой строке сможет выставить географическую при надлежность определённому региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона.

Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

*** geo_data = {
‘Центр’: [‘москва’, ‘тула’, ‘ярославль’],
‘Северо-Запад’: [‘петербург’, ‘псков’, ‘мурманск’],
‘Дальний Восток’: [‘владивосток’, ‘сахалин’, ‘хабаровск’]
}

#### Результат классификации запишите в отдельный столбец region.

In [57]:
df_keywords = pd.read_csv('C:\\Users\\User\\Desktop\\Аналитик данных\\ДЗ\\ДЗ 10 классы\\keywords.csv', sep=',', encoding='utf-8')

In [58]:
df_keywords.head(5)

         keyword     shows
0             вк  64292779
1  одноклассники  63810309
2          порно  41747114
3           ютуб  39995567
4      вконтакте  21014195

In [59]:
cities = ['москва', 'тула', 'ярославль', 'петербург', 'псков', 'мурманск', 'владивосток', 'сахалин', 'хабаровск']

In [60]:
df_keywords.query('keyword in @cities')

           keyword   shows
1259        москва  153050
5858   владивосток   43038
6075     ярославль   41720
8977      мурманск   29984
9084     хабаровск   29655
11222        псков   24885
11785         тула   23898
20823    петербург   14859
21445      сахалин   14494

In [61]:
centr = ['москва', 'тула', 'ярославль']
sev_zap = ['петербург', 'псков', 'мурманск']
dal_vost = ['владивосток', 'сахалин', 'хабаровск']

In [62]:
# пишу функцию для принадлежности к региону
'''
geo_data = {
‘Центр’: [‘москва’, ‘тула’, ‘ярославль’],
‘Северо-Запад’: [‘петербург’, ‘псков’, ‘мурманск’],
‘Дальний Восток’: [‘владивосток’, ‘сахалин’, ‘хабаровск’]
}
'''
def geo_data(region):
    if region in centr:
        return 'Центр'
    elif region in sev_zap:
        return 'Северо-Запад'
    elif region in dal_vost:
        return 'Дальний Восток'
    else:
        return 'undefined'

In [63]:
# применяю функцию к файлу keywords
df_keywords['region_row'] = df_keywords['keyword'].apply(geo_data)
df_keywords

                       keyword     shows region_row
0                           вк  64292779  undefined
1                одноклассники  63810309  undefined
2                        порно  41747114  undefined
3                         ютуб  39995567  undefined
4                    вконтакте  21014195  undefined
...                        ...       ...        ...
99995   эльдорадо старый оскол      3705  undefined
99996      frigate для firefox      3630  undefined
99997                   укрсиб      3630  undefined
99998  погода в ялте на неделю      3688  undefined
99999                     ггму      3630  undefined

[100000 rows x 3 columns]

In [65]:
df_keywords[df_keywords['region_row'] == 'Северо-Запад']

         keyword  shows    region_row
8977    мурманск  29984  Северо-Запад
11222      псков  24885  Северо-Запад
20823  петербург  14859  Северо-Запад