###Задание 1
- Датасет для домашнего задания вы найдете в разделе “Материалы к домашнему заданию” к этому занятию.
- Определите, какому фильму было выставлено больше всего оценок 5.0.

In [1]:
import pandas as pd

In [2]:
df_movies = pd.read_csv('C:\\Users\\User\\Desktop\\Аналитик данных\\ДЗ\\10._pandas\\Задание 1\\movies.csv', sep=',', encoding='utf-8')

In [3]:
df_ratings = pd.read_csv('C:\\Users\\User\\Desktop\\Аналитик данных\\ДЗ\\10._pandas\\Задание 1\\ratings.csv', sep=',', encoding='utf-8')

In [4]:
df_movies.head(10) #чтение файла с фильмами

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

In [5]:
df_movies.info() #проверка на пустые значения

<class 'pandas.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   str
 2   genres   9742 non-null   str
dtypes: int64(1), str(2)
memory usage: 228.5 KB

In [6]:
df_ratings.head(10) # чтение файла с рейтингами

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931
5       1       70     3.0  964982400
6       1      101     5.0  964980868
7       1      110     4.0  964982176
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [7]:
df_ratings.info() #проверка на пустые значения

<class 'pandas.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

In [18]:
#фильтруем только фильмы с 5.0
df_ratings_5 = df_ratings[df_ratings['rating'] == 5.0]
df_ratings_5

        userId  movieId  rating   timestamp
3            1       47     5.0   964983815
4            1       50     5.0   964982931
6            1      101     5.0   964980868
8            1      151     5.0   964984041
9            1      157     5.0   964984100
...        ...      ...     ...         ...
100814     610   158238     5.0  1479545219
100829     610   164179     5.0  1493845631
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352

[13211 rows x 4 columns]

In [20]:
# сгруппировать по ИД фильма самое большое количество оценок 5.0
df_ratings_5_MID = df_ratings_5.groupby('movieId').count()
df_ratings_5_MID

         userId  rating  timestamp
movieId
1            47      47         47
2             7       7          7
3             6       6          6
5             3       3          3
6            24      24         24
...         ...     ...        ...
184245        1       1          1
185135        1       1          1
187593        4       4          4
187595        1       1          1
187717        1       1          1

[2954 rows x 3 columns]

In [17]:
#сортировка по количеству оценок 5.0 рейтинга и нахождение фильма
df_ratings_5_MID.sort_values('rating', ascending=False)

         userId  rating  timestamp
movieId
318         153     153        153
296         123     123        123
356         116     116        116
2571        109     109        109
260         104     104        104
...         ...     ...        ...
172585        1       1          1
184245        1       1          1
183897        1       1          1
180095        1       1          1
179819        1       1          1

[2954 rows x 3 columns]

In [67]:
print(df_movies[df_movies['movieId'] == 318])

     movieId                             title       genres
277      318  Shawshank Redemption, The (1994)  Crime|Drama

###Задание 2
- По данным файла power.csv (находится в “Материалы к домашнему заданию”) посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 год.
- Не учитывайте в расчётах отрицательные значения quantity.

In [68]:
df_power = pd.read_csv('C:\\Users\\User\\Desktop\\Аналитик данных\\ДЗ\\10._pandas\\Задание 2\\power.csv', sep=',', encoding='utf-8')
df_power.head(3)

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1

In [69]:
df_power.info()

<class 'pandas.DataFrame'>
RangeIndex: 1189482 entries, 0 to 1189481
Data columns (total 4 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   country   1189482 non-null  str
 1   year      1189482 non-null  int64
 2   quantity  1189482 non-null  float64
 3   category  1189482 non-null  int64
dtypes: float64(1), int64(2), str(1)
memory usage: 36.3 MB

In [39]:
df_transactions = pd.read_csv('C:\\Users\\User\\Desktop\\Аналитик данных\\ДЗ\\10._pandas\\Задание 2\\transactions.csv', sep=',', encoding='utf-8')
df_transactions.head(3)

   Year  Month    ID Product  Amount  Price  Total  Cost
0  2017      1  t001      A1       7   2904  20328  1200
1  2017      1  t002      A2       2   1896   3792  1100
2  2017      2  t003      A1       5   2904  14520  1200

In [70]:
#создаем список нужных условий
pribaltika = ['Latvia', 'Lithuania', 'Estonia']
category = [4, 12, 21]
years = [2005, 2006, 2007, 2008, 2009, 2010]

#Фильтр по странам и категориям и годам
df_power[df_power['country'] == 'Estonia']  #and 'category' == category and 'year' == years)

#Фильтр по условиям из переменных
df_pribaltika = df_power.query('country in @pribaltika and category in @category and year in @years')

In [71]:
df_pribaltika

          country  year  quantity  category
10617     Estonia  2008       1.0         4
10618     Estonia  2007       0.0         4
10619     Estonia  2006       0.0         4
10620     Estonia  2005       1.0         4
11156   Lithuania  2008       1.0         4
...           ...   ...       ...       ...
253982  Lithuania  2009      98.0        21
253983  Lithuania  2008      54.0        21
253984  Lithuania  2007      47.0        21
253985  Lithuania  2006      31.0        21
253986  Lithuania  2005       1.0        21

[411 rows x 4 columns]

In [74]:
df_pribaltika_pos = df_pribaltika[df_pribaltika['quantity'] > 0]
df_pribaltika_pos

          country  year  quantity  category
10617     Estonia  2008       1.0         4
10620     Estonia  2005       1.0         4
11156   Lithuania  2008       1.0         4
11158   Lithuania  2006       1.0         4
11159   Lithuania  2005       1.0         4
...           ...   ...       ...       ...
253982  Lithuania  2009      98.0        21
253983  Lithuania  2008      54.0        21
253984  Lithuania  2007      47.0        21
253985  Lithuania  2006      31.0        21
253986  Lithuania  2005       1.0        21

[347 rows x 4 columns]

In [75]:
total_pribaltika = df_pribaltika_pos['quantity'].sum()

In [76]:
print(total_pribaltika)

240580.0